<a href="https://colab.research.google.com/github/dhruvchaubey/ts1017data_analytics/blob/main/upcoming_flights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
from google.colab import files
uploaded = files.upload()

Saving Book3.xlsx to Book3.xlsx

In [25]:
import pandas as pd
import io

# Replace 'your_file.xlsx' with the actual uploaded filename
df = pd.read_excel(io.BytesIO(uploaded['Book3.xlsx']))

# Display the DataFrame
df.head()

,Join Date,Frequent Flier Number,First Name,Last Name,Flight Number,Flight Date,Departing City,Arrival City,Departure Time,Arrival Time,Departure Time Zone,Arrival Time Zone,Cost,Car Rental Addon $,Hotel Addon $
0,2009-10-07 00:00:00,9531726184,Megan,Brown,DL7263,2024-11-04 00:00:00,Berlin,Miaml,04:38:00,09:38:00,UTC,CST,998.55 BRL,197.5 BRL,419.24 BRL
1,1996-07-29 00:00:00,7654154528,William,Lee,DL685k,2024-11-04 00:00:00,Dubai,Hong Kong,22:38:00,08:38:00,UTC,UTk,283.62 AUD,256.04 AUD,302
2,1990-03-11 00:00:00,1035783281,Courtney,Valdez,DL8569,2025-01-03 00:00:00,Houston,Paris,00:38:00,10:38:00,PST,UTC,335.82 GBP,117.56 GBP,263.57 GBP
3,2002-12-16 00:00:00,787669065,Erik,Schneider,DL7894,2025-07-21 00:00:00,New York,Miami,23:38:00,10:38:00,EST,PSy,686.64 USD,77.29 USD,197.77 USD
4,NaN,2871854617,Alexander,Johnson,DL6365,2025-01-21 00:00:00,Dallas,New York,02:38:00,04:38:00,CST,EST,601.82 USD,161.71 USD,197.69 USD

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15078 entries, 0 to 15077
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Join Date              14325 non-null  object
 1   Frequent Flier Number  15078 non-null  int64
 2   First Name             14325 non-null  object
 3   Last Name              15078 non-null  object
 4   Flight Number          15078 non-null  object
 5   Flight Date            15078 non-null  object
 6   Departing City         15078 non-null  object
 7   Arrival City           14325 non-null  object
 8   Departure Time         14325 non-null  object
 9   Arrival Time           14325 non-null  object
 10  Departure Time Zone    15078 non-null  object
 11  Arrival Time Zone      15078 non-null  object
 12  Cost                   14325 non-null  object
 13  Car Rental Addon $     14325 non-null  object
 14  Hotel Addon $          14325 non-null  object
dtypes: int64(1), object(14)
memory usage: 1.7+ MB

In [27]:
df.columns = df.columns.str.strip()
df.columns

Index(['Join Date', 'Frequent Flier Number', 'First Name', 'Last Name',
       'Flight Number', 'Flight Date', 'Departing City', 'Arrival City',
       'Departure Time', 'Arrival Time', 'Departure Time Zone',
       'Arrival Time Zone', 'Cost', 'Car Rental Addon $', 'Hotel Addon $'],
      dtype='object')

Fixing the time zone values from the columns Departure time zone and Arrival time zones

In [37]:
# Create a mapping of regex patterns to their corresponding timezone values
timezone_mapping = {
    r'^UT.*$': 'UTC',  # Any value starting with 'UT' to 'UTC'
    r'^MS.*$': 'MST',  # Any value starting with 'MS' to 'MST'
    r'^ES.*$': 'EST',  # Any value starting with 'ES' to 'EST'
    r'^PS.*$': 'PST',  # Any value starting with 'PS' to 'PST'
    r'^CS.*$': 'CST',  # Any value starting with 'CS' to 'CST'
}

# Replace using the mapping
for pattern, replacement in timezone_mapping.items():
    df['Arrival Time Zone'] = df['Arrival Time Zone'].replace(to_replace=pattern, value=replacement, regex=True)

# Show the resulting DataFrame
#print(df['Departure Time Zone'])

timezone_mapping = {
    r'^UT.*$': 'UTC',  # Any value starting with 'UT' to 'UTC'
    r'^MS.*$': 'MST',  # Any value starting with 'MS' to 'MST'
    r'^ES.*$': 'EST',  # Any value starting with 'ES' to 'EST'
    r'^PS.*$': 'PST',  # Any value starting with 'PS' to 'PST'
    r'^CS.*$': 'CST',  # Any value starting with 'CS' to 'CST'
}

# Replace using the mapping
for pattern, replacement in timezone_mapping.items():
    df['Departure Time Zone'] = df['Departure Time Zone'].replace(to_replace=pattern, value=replacement, regex=True)

# Show the resulting DataFrame
#print(df['Departure Time Zone'])

df.head()

,Join Date,Frequent Flier Number,First Name,Last Name,Flight Number,Flight Date,Departing City,Arrival City,Departure Time,Arrival Time,Departure Time Zone,Arrival Time Zone,Cost,Car Rental Addon $,Hotel Addon $
0,2009-10-07 00:00:00,9531726184,Megan,Brown,DL7263,2024-11-04 00:00:00,Berlin,Miaml,04:38:00,09:38:00,UTC,CST,998.55 BRL,197.5 BRL,419.24 BRL
1,1996-07-29 00:00:00,7654154528,William,Lee,DL685k,2024-11-04 00:00:00,Dubai,Hong Kong,22:38:00,08:38:00,UTC,UTC,283.62 AUD,256.04 AUD,302
2,1990-03-11 00:00:00,1035783281,Courtney,Valdez,DL8569,2025-01-03 00:00:00,Houston,Paris,00:38:00,10:38:00,PST,UTC,335.82 GBP,117.56 GBP,263.57 GBP
3,2002-12-16 00:00:00,787669065,Erik,Schneider,DL7894,2025-07-21 00:00:00,New York,Miami,23:38:00,10:38:00,EST,PST,686.64 USD,77.29 USD,197.77 USD
4,NaN,2871854617,Alexander,Johnson,DL6365,2025-01-21 00:00:00,Dallas,New York,02:38:00,04:38:00,CST,EST,601.82 USD,161.71 USD,197.69 USD

Let's try the same function to solve the city values discrepancies

In [41]:
city_mapping = {
    r'^Atlant.*$': 'Atlanta',
    r'^Berli.*$': 'Berlin',
    r'^Bosto.*$': 'Boston',
    r'^Chicag.*$': 'Chicago',
    r'^Dalla.*$': 'Dallas',
    r'^Duba.*$': 'Dubai',
    r'^Hong Kon.*$': 'Hong Kong',
    r'^Housto.*$': 'Houston',
    r'^Londo.*$': 'London',
    r'^Los Angele.*$': 'Los Angeles',
    r'^Mexico Cit.*$': 'Mexico City',
    r'^Miam.*$': 'Miami',
    r'^New Yor.*$': 'New York',
    r'^Pari.*$': 'Paris',
    r'^Rio De Janeri.*$': 'Rio De Janerio',
    r'^San Fransisc.*$': 'San Fransico',
    r'^Sydne.*$': 'Sydney',
    r'^Toky.*$': 'Tokyo',
    r'^Toront.*$': 'Toronto',
    r'^Washington D.C.*$': 'Washington D.C.',

}
for pattern, replacement in city_mapping.items():
    df['Departing City'] = df['Departing City'].replace(to_replace=pattern, value=replacement, regex=True)
    df['Arrival City'] = df['Arrival City'].replace(to_replace=pattern, value=replacement, regex=True)

df.head(10)

,Join Date,Frequent Flier Number,First Name,Last Name,Flight Number,Flight Date,Departing City,Arrival City,Departure Time,Arrival Time,Departure Time Zone,Arrival Time Zone,Cost,Car Rental Addon $,Hotel Addon $
0,2009-10-07 00:00:00,9531726184,Megan,Brown,DL7263,2024-11-04 00:00:00,Berlin,Miami,04:38:00,09:38:00,UTC,CST,998.55 BRL,197.5 BRL,419.24 BRL
1,1996-07-29 00:00:00,7654154528,William,Lee,DL685k,2024-11-04 00:00:00,Dubai,Hong Kong,22:38:00,08:38:00,UTC,UTC,283.62 AUD,256.04 AUD,302
2,1990-03-11 00:00:00,1035783281,Courtney,Valdez,DL8569,2025-01-03 00:00:00,Houston,Paris,00:38:00,10:38:00,PST,UTC,335.82 GBP,117.56 GBP,263.57 GBP
3,2002-12-16 00:00:00,787669065,Erik,Schneider,DL7894,2025-07-21 00:00:00,New York,Miami,23:38:00,10:38:00,EST,PST,686.64 USD,77.29 USD,197.77 USD
4,NaN,2871854617,Alexander,Johnson,DL6365,2025-01-21 00:00:00,Dallas,New York,02:38:00,04:38:00,CST,EST,601.82 USD,161.71 USD,197.69 USD
5,2004-10-2w,5945442472,Thomas,Boone,DL2990,2025-05-03 00:00:00,London,Houston,07:38:00,10:38:00,UTC,MST,990.57 USz,55.78 USD,331.42 USD
6,2007-04-17 00:00:00,9061044818,Mark,Hernandez,DL8933,2025-08-06 00:00:00,New York,London,NaN,06:38:00,EST,UTC,973.39 USD,84.95 USD,474.18 USD
7,402,4178900661,Kaitlyn,Montoya,DL872f,2024-10-14 00:00:00,Washington D.C.,Atlanta,09:38:00,14:38:00,PST,MST,873.62 USD,NaN,211.54 USD
8,1988-06-16 00:00:00,3287980520,Amy,Smith,DL1165,2025-04-23 00:00:00,Mexico City,NaN,04:38:00,14:38:00,UTC,UTC,708.67 CAD,102.92 CAD,143.16 CAD
9,NaN,8798662645,Cheryl,Cruz,DL6018,2024-09-29 00:00:00,Toronto,London,08:38:00,17:38:00,UTC,UTC,137.1 HKD,111.58 HKD,423.0 HKD